apiVersion: v1
kind: ReplicationController
metadata:
  name: neo4j-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      nodeName: k8s-node-1
      containers:
        - image: neo4j:3.5
          name: neo4j
          ports:
            - containerPort: 7474
            - containerPort: 7687
