version: '3.4'
services:
  neo4j:
    image: neo4j:3.5
    ports:
      - '7475:7474'
      - '7688:7687'
    networks:
      - tecstaurant_net
  catalog_service:
    build: ./services/catalog-service
    volumes:
      - ./services/catalog-service:/usr/src/service
    ports:
      - '4001:4000'
    networks:
      - tecstaurant_net
  report_service:
    build: ./services/report-service
    volumes:
      - ./services/report-service:/usr/src/service
    ports:
      - '5000:80'
    networks:
      - tecstaurant_net
networks:
  tecstaurant_net:
    driver: bridge
