apiVersion: v1
kind: ReplicationController
metadata:
  name: neo4j-tecstaurant
spec:
  replicas: 1
  selector:
    app: neo4j
  template:
    metadata:
      name: neo4j
      labels:
        app: neo4j
    spec:
    nodeName: k8s-node-1
      containers:
        - image: neo4j:3.5
          name: neo4j
          ports:
            - containerPort: 7474
            - containerPort: 7687
