// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package order_service

type EraseOrder struct {
	Orderid int `json:"orderid"`
}

type NewOrder struct {
	Date       string        `json:"date"`
	Rating     float64       `json:"rating"`
	TotalPrice float64       `json:"totalPrice"`
	ClientID   int           `json:"clientId"`
	LocationID int           `json:"locationId"`
	Products   []*NewProduct `json:"products"`
}

type NewProduct struct {
	ProductID int    `json:"productId"`
	Details   string `json:"details"`
}
