// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package order_service

type NewOrder struct {
	Date       string   `json:"date"`
	Rating     *float64 `json:"rating"`
	TotalPrice float64  `json:"totalPrice"`
}
