---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  labels:
    app: catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - image: tecstaurant/catalog-service:latest
          name: catalog
          resources:
            limits:
              cpu: "100m"
            requests:
              cpu: "100m"
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-svc
spec:
  selector:
    app: catalog
  ports:
    - name: 'http'
      port: 4000
      targetPort: 4000
---

