---
apiVersion: v1
kind: ReplicationController
metadata:
  name: catalog-rc
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - image: tecstaurant/catalog-service:initial
          name: catalog
          ports:
            - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-svc
spec:
  selector:
    app: catalog
  ports:
    - name: 'API'
      port: 4000
      targetPort: 4000
---

