---
apiVersion: v1
kind: ReplicationController
metadata:
  name: neo4j-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      nodeName: kworker2
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-claim
      containers:
        - image: neo4j:3.5
          env:
            - name: NEO4J_AUTH
              value: 'neo4j/tecstaurantneodbadmin01'
          name: neo4j
          ports:
            - containerPort: 7474
            - containerPort: 7687
          volumeMounts:
            - name: neo4j-data
              mountPath: /var/lib/neo4j/data
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-svc
spec:
  selector:
    app: neo4j
  ports:
    - name: 'browser'
      port: 7474
      targetPort: 7474
    - name: 'bolt'
      port: 7687
      targetPort: 7687
---

