---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/neo4j'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---

